# Generated by Django 5.1.1 on 2024-09-21 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('profesional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateTimeField()),
                ('duracion', models.DurationField(help_text='Duración de la cita (HH:MM:SS)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_citas', to='clientes.cliente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_citas', to='profesional.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='NotaCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField()),
                ('fecha_nota', models.DateTimeField(auto_now_add=True)),
                ('reserva_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='reserva.reservacita')),
            ],
        ),
    ]
